apply plugin: 'jacoco'

jacoco {
    toolVersion = "0.7.2.201409121644"
    // WARNING: v0.7.3+ breaks Robolectric coverage support: https://github.com/jacoco/jacoco/issues/288
}

project.afterEvaluate {
    android.sourceSets.all { sourceSet ->
        def sourceSetName = sourceSet.name
        def buildTypeName = ""
        def productFlavorName = ""

        if (sourceSetName.startsWith("test")) {
            sourceSetName = sourceSetName - "test"
            if (sourceSetName) {
                productFlavorName = sourceSetName.take(sourceSetName.length() - 4)
            }
            buildTypeName = sourceSetName.takeRight(4)
        }

        def sourceName = productFlavorName ? "${productFlavorName}${buildTypeName.capitalize()}" : buildTypeName
        def testTaskName = "test${sourceName.capitalize()}UnitTest"
        def coverageTaskName = "${testTaskName}Coverage"

        task(coverageTaskName, type: JacocoReport, dependsOn: "$testTaskName") {
            group = "Reporting"
            description = "Generate Jacoco coverage reports on the ${sourceName.capitalize()} build."

            def classDir = fileTree(
                    dir: "${sourceSet.java.srcDirs[0]}",
                    excludes: [
                            '**/R.class',
                            '**/R$*.class',
                            '**/*$ViewInjector*.*',
                            '**/BuildConfig.*',
                            '**/Manifest*.*',
                            'android/databinding/**',
                            'com/android/databinding/**',
                            '**/AnnotationDatabaseImpl.class' // Generated by RoboBlender
                    ]
            )

            classDirectories.setFrom(classDir)
            def coverageSourceDirs = sourceSet.java.srcDirs
            sourceDirectories.setFrom(coverageSourceDirs)
            executionData.setFrom(fileTree(dir: "${project.buildDir}/jacoco", includes: ["**/${testTaskName}.exec"]))

            reports {
                xml.enabled = true
                html.enabled = true
            }
        }
    }
}
